name: tests
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-18.04
    timeout-minutes: 10
    env:
      RAILS_ENV: test
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Setup NPM
        uses: actions/setup-node@v1
      - name: Compile assets
        run: bundle exec rake assets:precompile > /dev/null 2>&1
      - name: Run test suite
        run: bin/rspec spec
